/* eslint-disable @typescript-eslint/no-var-requires */
const { pick, omit } = require("lodash")
const colors = require("tailwindcss/colors")
const defaultTheme = require("tailwindcss/defaultTheme")

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    screens: {
      "2xs": { min: "0px", max: "319.98px" },
      xs: "320px",
      sm: "576px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": { min: "1536px", max: "1920px" },
    },
    fontFamily: {
      storybook: ["var(--font-inputmono)", ...defaultTheme.fontFamily.sans],
      body: ["var(--font-inputmono)", ...defaultTheme.fontFamily.sans],
      inputMono: ["var(--font-inputmono)", ...defaultTheme.fontFamily.sans],
      menlo: ["var(--font-menlo)", ...defaultTheme.fontFamily.sans],
      sfProText: ["var(--font-sfprotext)"],
    },
    colors: {
      base: {
        DEFAULT: "var(--color-base-01)",
        "01": "var(--color-base-01)",
        "02": "var(--color-base-02)",
        "03": "var(--color-base-03)",
        "04": "var(--color-base-04)",
        "05": "var(--color-base-05)",
        "06": "var(--color-base-06)",
        "07": "var(--color-base-07)",
        "08": "var(--color-base-08)",
        "09": "var(--color-base-09)",
        10: "var(--color-base-10)",
        11: "var(--color-base-11)",
        12: "var(--color-base-12)",
        13: "var(--color-base-13)",
        14: "var(--color-base-14)",
        15: "var(--color-base-15)",
        16: "var(--color-base-16)",
        17: "var(--color-base-17)",
        18: "var(--color-base-18)",
        19: "var(--color-base-19)",
        20: "var(--color-base-20)",
        21: "var(--color-base-21)",
      },
      blue: {
        DEFAULT: "var(--color-blue-01)",
        "01": "var(--color-blue-01)",
        "02": "var(--color-blue-02)",
        "03": "var(--color-blue-03)",
        "04": "var(--color-blue-04)",
        "05": "var(--color-blue-05)",
        "06": "var(--color-blue-06)",
        "07": "var(--color-blue-07)",
        "08": "var(--color-blue-08)",
        "09": "var(--color-blue-09)",
        10: "var(--color-blue-10)",
        11: "var(--color-blue-11)",
      },
      red: {
        DEFAULT: "var(--color-red-01)",
        "01": "var(--color-red-01)",
        "02": "var(--color-red-02)",
        "03": "var(--color-red-03)",
        "04": "var(--color-red-04)",
      },
      green: {
        DEFAULT: "var(--color-green-01)",
        "01": "var(--color-green-01)",
        "02": "var(--color-green-02)",
        "03": "var(--color-green-03)",
        "04": "var(--color-green-04)",
        "05": "var(--color-green-05)",
      },
      purple: {
        DEFAULT: "var(--color-purple-01)",
        "01": "var(--color-purple-01)",
        "02": "var(--color-purple-02)",
        "03": "var(--color-purple-03)",
        "04": "var(--color-purple-04)",
        "05": "var(--color-purple-05)",
      },
      yellow: {
        DEFAULT: "var(--color-yellow-01)",
        "01": "var(--color-yellow-01)",
        "02": "var(--color-yellow-02)",
        "03": "var(--color-yellow-03)",
        "04": "var(--color-yellow-04)",
        "05": "var(--color-yellow-05)",
      },
      gray: {
        DEFAULT: "var(--color-gray-01)",
        "01": "var(--color-gray-01)",
        "02": "var(--color-gray-02)",
        "03": "var(--color-gray-03)",
      },
      seti: {
        DEFAULT: "var(--color-seti-blue)",
        blue: "var(--color-seti-blue)",
        green: "var(--color-seti-green)",
        orange: "var(--color-seti-orange)",
        pink: "var(--color-seti-pink)",
        red: "var(--color-seti-red)",
        steel: "var(--color-seti-steel)",
        yellow: "var(--color-seti-yellow)",
        purple: "var(--color-seti-purple)",
        ignore: "var(--color-seti-ignore)",
        white: "var(--color-seti-white)",
        gray: "var(--color-seti-gray)",
      },
    },
    extend: {
      fontFamily: {
        body: [
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "system-ui",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "Noto Sans",
          "sans-serif",
          "Apple Color Emoji",
          "Segoe UI Emoji",
          "Segoe UI Symbol",
          "Noto Color Emoji",
        ],
        sans: [
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "system-ui",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "Noto Sans",
          "sans-serif",
          "Apple Color Emoji",
          "Segoe UI Emoji",
          "Segoe UI Symbol",
          "Noto Color Emoji",
        ],
      },
      borderWidth: {
        DEFAULT: "1px",
        0: "0",
        2: "2px",
        3: "3px",
        4: "4px",
        6: "6px",
        8: "8px",
      },
      minHeight: {
        ...defaultTheme.height,
      },
      minWidth: {
        ...defaultTheme.width,
      },
    },
  },
  plugins: [],
  future: {
    hoverOnlyWhenSupported: true,
  },
}
