export const BASECOLOR = {
  base: {
    DEFAULT: "var(--color-base-01)",
    "01": "var(--color-base-01)",
    "02": "var(--color-base-02)",
    "03": "var(--color-base-03)",
    "04": "var(--color-base-04)",
    "05": "var(--color-base-05)",
    "06": "var(--color-base-06)",
    "07": "var(--color-base-07)",
    "08": "var(--color-base-08)",
    "09": "var(--color-base-09)",
    10: "var(--color-base-10)",
    11: "var(--color-base-11)",
    12: "var(--color-base-12)",
    13: "var(--color-base-13)",
    14: "var(--color-base-14)",
    15: "var(--color-base-15)",
    16: "var(--color-base-16)",
    17: "var(--color-base-17)",
    18: "var(--color-base-18)",
    19: "var(--color-base-19)",
    20: "var(--color-base-20)",
    21: "var(--color-base-21)",
  },
}

export const ACCENTS = {
  blue: {
    DEFAULT: "var(--color-blue-01)",
    "01": "var(--color-blue-01)",
    "02": "var(--color-blue-02)",
    "03": "var(--color-blue-03)",
    "04": "var(--color-blue-04)",
    "05": "var(--color-blue-05)",
    "06": "var(--color-blue-06)",
    "07": "var(--color-blue-07)",
    "08": "var(--color-blue-08)",
    "09": "var(--color-blue-09)",
    10: "var(--color-blue-10)",
    11: "var(--color-blue-11)",
  },
  red: {
    DEFAULT: "var(--color-red-01)",
    "01": "var(--color-red-01)",
    "02": "var(--color-red-02)",
    "03": "var(--color-red-03)",
    "04": "var(--color-red-04)",
  },
  green: {
    DEFAULT: "var(--color-green-01)",
    "01": "var(--color-green-01)",
    "02": "var(--color-green-02)",
    "03": "var(--color-green-03)",
    "04": "var(--color-green-04)",
    "05": "var(--color-green-05)",
  },
  purple: {
    DEFAULT: "var(--color-purple-01)",
    "01": "var(--color-purple-01)",
    "02": "var(--color-purple-02)",
    "03": "var(--color-purple-03)",
    "04": "var(--color-purple-04)",
    "05": "var(--color-purple-05)",
  },
  yellow: {
    DEFAULT: "var(--color-yellow-01)",
    "01": "var(--color-yellow-01)",
    "02": "var(--color-yellow-02)",
    "03": "var(--color-yellow-03)",
    "04": "var(--color-yellow-04)",
    "05": "var(--color-yellow-05)",
  },
  gray: {
    DEFAULT: "var(--color-gray-01)",
    "01": "var(--color-gray-01)",
    "02": "var(--color-gray-02)",
    "03": "var(--color-gray-03)",
  },
  seti: {
    DEFAULT: "var(--color-seti-blue)",
    blue: "var(--color-seti-blue)",
    green: "var(--color-seti-green)",
    orange: "var(--color-seti-orange)",
    pink: "var(--color-seti-pink)",
    red: "var(--color-seti-red)",
    steel: "var(--color-seti-steel)",
    yellow: "var(--color-seti-yellow)",
    purple: "var(--color-seti-purple)",
    ignore: "var(--color-seti-ignore)",
    white: "var(--color-seti-white)",
    gray: "var(--color-seti-gray)",
  },
}
