export const CODICONS = [
  "account ",
  "activate-breakpoints ",
  "add ",
  "archive ",
  "arrow-both ",
  "arrow-circle-down ",
  "arrow-circle-left ",
  "arrow-circle-right ",
  "arrow-circle-up ",
  "arrow-down ",
  "arrow-left ",
  "arrow-right ",
  "arrow-small-down ",
  "arrow-small-left ",
  "arrow-small-right ",
  "arrow-small-up ",
  "arrow-swap ",
  "arrow-up ",
  "azure-devops ",
  "azure ",
  "beaker-stop ",
  "beaker ",
  "bell-dot ",
  "bell-slash-dot ",
  "bell-slash ",
  "bell ",
  "bold ",
  "book ",
  "bookmark ",
  "bracket-dot ",
  "bracket-error ",
  "briefcase ",
  "broadcast ",
  "browser ",
  "bug ",
  "calendar ",
  "call-incoming ",
  "call-outgoing ",
  "case-sensitive ",
  "check-all ",
  "check ",
  "checklist ",
  "chevron-down ",
  "chevron-left ",
  "chevron-right ",
  "chevron-up ",
  "chrome-close ",
  "chrome-maximize ",
  "chrome-minimize ",
  "chrome-restore ",
  "circle-filled ",
  "circle-large-filled ",
  "circle-large ",
  "circle-slash ",
  "circle-small-filled ",
  "circle-small ",
  "circle ",
  "circuit-board ",
  "clear-all ",
  "clippy ",
  "close-all ",
  "close ",
  "cloud-download ",
  "cloud-upload ",
  "cloud ",
  "code ",
  "collapse-all ",
  "color-mode ",
  "combine ",
  "comment-discussion ",
  "comment-draft ",
  "comment-unresolved ",
  "comment ",
  "compass-active ",
  "compass-dot ",
  "compass ",
  "copy ",
  "credit-card ",
  "dash ",
  "dashboard ",
  "database ",
  "debug-all ",
  "debug-alt-small ",
  "debug-alt ",
  "debug-breakpoint-conditional-unverified ",
  "debug-breakpoint-conditional ",
  "debug-breakpoint-data-unverified ",
  "debug-breakpoint-data ",
  "debug-breakpoint-function-unverified ",
  "debug-breakpoint-function ",
  "debug-breakpoint-log-unverified ",
  "debug-breakpoint-log ",
  "debug-breakpoint-unsupported ",
  "debug-console ",
  "debug-continue-small ",
  "debug-continue ",
  "debug-coverage ",
  "debug-disconnect ",
  "debug-line-by-line ",
  "debug-pause ",
  "debug-rerun ",
  "debug-restart-frame ",
  "debug-restart ",
  "debug-reverse-continue ",
  "debug-stackframe-active ",
  "debug-stackframe ",
  "debug-start ",
  "debug-step-back ",
  "debug-step-into ",
  "debug-step-out ",
  "debug-step-over ",
  "debug-stop ",
  "debug ",
  "desktop-download ",
  "device-camera-video ",
  "device-camera ",
  "device-mobile ",
  "diff-added ",
  "diff-ignored ",
  "diff-modified ",
  "diff-removed ",
  "diff-renamed ",
  "diff ",
  "discard ",
  "edit ",
  "editor-layout ",
  "ellipsis ",
  "empty-window ",
  "error-small ",
  "error ",
  "exclude ",
  "expand-all ",
  "export ",
  "extensions ",
  "eye-closed ",
  "eye ",
  "feedback ",
  "file-binary ",
  "file-code ",
  "file-media ",
  "file-pdf ",
  "file-submodule ",
  "file-symlink-directory ",
  "file-symlink-file ",
  "file-zip ",
  "file ",
  "files ",
  "filter-filled ",
  "filter ",
  "flame ",
  "fold-down ",
  "fold-up ",
  "fold ",
  "folder-active ",
  "folder-library ",
  "folder-opened ",
  "folder ",
  "gear ",
  "gift ",
  "gist-secret ",
  "gist ",
  "git-commit ",
  "git-compare ",
  "git-merge ",
  "git-pull-request-closed ",
  "git-pull-request-create ",
  "git-pull-request-draft ",
  "git-pull-request-go-to-changes ",
  "git-pull-request-new-changes ",
  "git-pull-request ",
  "github-action ",
  "github-alt ",
  "github-inverted ",
  "github ",
  "globe ",
  "go-to-file ",
  "grabber ",
  "graph-left ",
  "graph-line ",
  "graph-scatter ",
  "graph ",
  "gripper ",
  "group-by-ref-type ",
  "heart-filled ",
  "heart ",
  "history ",
  "home ",
  "horizontal-rule ",
  "hubot ",
  "inbox ",
  "indent ",
  "info ",
  "insert ",
  "inspect ",
  "issue-draft ",
  "issue-reopened ",
  "issues ",
  "italic ",
  "jersey ",
  "json ",
  "kebab-vertical ",
  "key ",
  "law ",
  "layers-active ",
  "layers-dot ",
  "layers ",
  "layout-activitybar-left ",
  "layout-activitybar-right ",
  "layout-centered ",
  "layout-menubar ",
  "layout-panel-center ",
  "layout-panel-justify ",
  "layout-panel-left ",
  "layout-panel-off ",
  "layout-panel-right ",
  "layout-panel ",
  "layout-sidebar-left-off ",
  "layout-sidebar-left ",
  "layout-sidebar-right-off ",
  "layout-sidebar-right ",
  "layout-statusbar ",
  "layout ",
  "library ",
  "lightbulb-autofix ",
  "lightbulb ",
  "link-external ",
  "link ",
  "list-filter ",
  "list-flat ",
  "list-ordered ",
  "list-selection ",
  "list-tree ",
  "list-unordered ",
  "live-share ",
  "loading ",
  "location ",
  "lock-small ",
  "lock ",
  "magnet ",
  "mail-read ",
  "mail ",
  "map-filled ",
  "map ",
  "markdown ",
  "megaphone ",
  "mention ",
  "menu ",
  "merge ",
  "milestone ",
  "mirror ",
  "mortar-board ",
  "move ",
  "multiple-windows ",
  "mute ",
  "new-file ",
  "new-folder ",
  "newline ",
  "no-newline ",
  "note ",
  "notebook-template ",
  "notebook ",
  "octoface ",
  "open-preview ",
  "organization ",
  "output ",
  "package ",
  "paintcan ",
  "pass-filled ",
  "pass ",
  "person-add ",
  "person ",
  "pie-chart ",
  "pin ",
  "pinned-dirty ",
  "pinned ",
  "play-circle ",
  "play ",
  "plug ",
  "preserve-case ",
  "preview ",
  "primitive-square ",
  "project ",
  "pulse ",
  "question ",
  "quote ",
  "radio-tower ",
  "reactions ",
  "record-keys ",
  "record-small ",
  "record ",
  "redo ",
  "references ",
  "refresh ",
  "regex ",
  "remote-explorer ",
  "remote ",
  "remove ",
  "replace-all ",
  "replace ",
  "reply ",
  "repo-clone ",
  "repo-force-push ",
  "repo-forked ",
  "repo-pull ",
  "repo-push ",
  "repo ",
  "report ",
  "request-changes ",
  "rocket ",
  "root-folder-opened ",
  "root-folder ",
  "rss ",
  "ruby ",
  "run-above ",
  "run-all ",
  "run-below ",
  "run-errors ",
  "save-all ",
  "save-as ",
  "save ",
  "screen-full ",
  "screen-normal ",
  "search-fuzzy ",
  "search-stop ",
  "search ",
  "send ",
  "server-environment ",
  "server-process ",
  "server ",
  "settings-gear ",
  "settings ",
  "shield ",
  "sign-in ",
  "sign-out ",
  "smiley ",
  "sort-precedence ",
  "source-control ",
  "sparkle ",
  "split-horizontal ",
  "split-vertical ",
  "squirrel ",
  "star-empty ",
  "star-full ",
  "star-half ",
  "stop-circle ",
  "symbol-array ",
  "symbol-boolean ",
  "symbol-class ",
  "symbol-color ",
  "symbol-constant ",
  "symbol-enum-member ",
  "symbol-enum ",
  "symbol-event ",
  "symbol-field ",
  "symbol-file ",
  "symbol-interface ",
  "symbol-key ",
  "symbol-keyword ",
  "symbol-method ",
  "symbol-misc ",
  "symbol-namespace ",
  "symbol-numeric ",
  "symbol-operator ",
  "symbol-parameter ",
  "symbol-property ",
  "symbol-ruler ",
  "symbol-snippet ",
  "symbol-string ",
  "symbol-structure ",
  "symbol-variable ",
  "sync-ignored ",
  "sync ",
  "table ",
  "tag ",
  "target ",
  "tasklist ",
  "telescope ",
  "terminal-bash ",
  "terminal-cmd ",
  "terminal-debian ",
  "terminal-linux ",
  "terminal-powershell ",
  "terminal-tmux ",
  "terminal-ubuntu ",
  "terminal ",
  "text-size ",
  "three-bars ",
  "thumbsdown ",
  "thumbsup ",
  "tools ",
  "trash ",
  "triangle-down ",
  "triangle-left ",
  "triangle-right ",
  "triangle-up ",
  "twitter ",
  "type-hierarchy-sub ",
  "type-hierarchy-super ",
  "type-hierarchy ",
  "unfold ",
  "ungroup-by-ref-type ",
  "unlock ",
  "unmute ",
  "unverified ",
  "variable-group ",
  "verified-filled ",
  "verified ",
  "versions ",
  "vm-active ",
  "vm-connect ",
  "vm-outline ",
  "vm-running ",
  "vm ",
  "wand ",
  "warning ",
  "watch ",
  "whitespace ",
  "whole-word ",
  "window ",
  "word-wrap ",
  "workspace-trusted ",
  "workspace-unknown ",
  "workspace-untrusted ",
  "zoom-in ",
  "zoom-out",
]

export const SETI_ICONS = [
  { R: "E001" },
  { apple: "E002" },
  { argdown: "E003" },
  { asm: "E004" },
  { audio: "E005" },
  { babel: "E006" },
  { bazel: "E007" },
  { bicep: "E008" },
  { bower: "E009" },
  { bsl: "E00A" },
  { "c-sharp": "E00B" },
  { c: "E00C" },
  { cake: "E00D" },
  { cake_php: "E00E" },
  { "checkbox-unchecked": "E00F" },
  { checkbox: "E010" },
  { cjsx: "E011" },
  { clock: "E012" },
  { clojure: "E013" },
  { "code-climate": "E014" },
  { "code-search": "E015" },
  { coffee: "E016" },
  { coffee_erb: "E017" },
  { coldfusion: "E018" },
  { config: "E019" },
  { cpp: "E01A" },
  { crystal: "E01B" },
  { crystal_embedded: "E01C" },
  { css: "E01D" },
  { csv: "E01E" },
  { cu: "E01F" },
  { d: "E020" },
  { dart: "E021" },
  { db: "E022" },
  { default: "E023" },
  { "deprecation-cop": "E024" },
  { docker: "E025" },
  { editorconfig: "E026" },
  { ejs: "E027" },
  { elixir: "E028" },
  { elixir_script: "E029" },
  { elm: "E02A" },
  { error: "E02B" },
  { eslint: "E02C" },
  { ethereum: "E02D" },
  { "f-sharp": "E02E" },
  { favicon: "E02F" },
  { firebase: "E030" },
  { firefox: "E031" },
  { folder: "E032" },
  { font: "E033" },
  { git: "E034" },
  { git_folder: "E035" },
  { git_ignore: "E036" },
  { github: "E037" },
  { gitlab: "E038" },
  { go: "E039" },
  { go2: "E03A" },
  { godot: "E03B" },
  { gradle: "E03C" },
  { grails: "E03D" },
  { graphql: "E03E" },
  { grunt: "E03F" },
  { gulp: "E040" },
  { hacklang: "E041" },
  { haml: "E042" },
  { happenings: "E043" },
  { haskell: "E044" },
  { haxe: "E045" },
  { heroku: "E046" },
  { hex: "E047" },
  { html: "E048" },
  { html_erb: "E049" },
  { ignored: "E04A" },
  { illustrator: "E04B" },
  { image: "E04C" },
  { info: "E04D" },
  { ionic: "E04E" },
  { jade: "E04F" },
  { java: "E050" },
  { javascript: "E051" },
  { jenkins: "E052" },
  { jinja: "E053" },
  { js_erb: "E054" },
  { json: "E055" },
  { julia: "E056" },
  { karma: "E057" },
  { kotlin: "E058" },
  { less: "E059" },
  { license: "E05A" },
  { liquid: "E05B" },
  { livescript: "E05C" },
  { lock: "E05D" },
  { lua: "E05E" },
  { makefile: "E05F" },
  { markdown: "E060" },
  { maven: "E061" },
  { mdo: "E062" },
  { mustache: "E063" },
  { "new-file": "E064" },
  { nim: "E065" },
  { notebook: "E066" },
  { npm: "E067" },
  { npm_ignored: "E068" },
  { nunjucks: "E069" },
  { ocaml: "E06A" },
  { odata: "E06B" },
  { pddl: "E06C" },
  { pdf: "E06D" },
  { perl: "E06E" },
  { photoshop: "E06F" },
  { php: "E070" },
  { pipeline: "E071" },
  { plan: "E072" },
  { platformio: "E073" },
  { powershell: "E074" },
  { prisma: "E075" },
  { project: "E076" },
  { prolog: "E077" },
  { pug: "E078" },
  { puppet: "E079" },
  { purescript: "E07A" },
  { python: "E07B" },
  { rails: "E07C" },
  { react: "E07D" },
  { reasonml: "E07E" },
  { rescript: "E07F" },
  { rollup: "E080" },
  { ruby: "E081" },
  { rust: "E082" },
  { salesforce: "E083" },
  { sass: "E084" },
  { sbt: "E085" },
  { scala: "E086" },
  { search: "E087" },
  { settings: "E088" },
  { shell: "E089" },
  { slim: "E08A" },
  { smarty: "E08B" },
  { spring: "E08C" },
  { stylelint: "E08D" },
  { stylus: "E08E" },
  { sublime: "E08F" },
  { svelte: "E090" },
  { svg: "E091" },
  { swift: "E092" },
  { terraform: "E093" },
  { tex: "E094" },
  { "time-cop": "E095" },
  { todo: "E096" },
  { tsconfig: "E097" },
  { twig: "E098" },
  { typescript: "E099" },
  { vala: "E09A" },
  { video: "E09B" },
  { vue: "E09C" },
  { wasm: "E09D" },
  { wat: "E09E" },
  { webpack: "E09F" },
  { wgt: "E0A0" },
  { windows: "E0A1" },
  { word: "E0A2" },
  { xls: "E0A3" },
  { xml: "E0A4" },
  { yarn: "E0A5" },
  { yml: "E0A6" },
  { zig: "E0A7" },
  { zip: "E0A8" },
]
