export const TYPOGRAPHY = {
  h1: {
    title: "Heading 1",
    description: "26px Medium",
    useCase: "Extension title",
    className: "font-sfProText text-[26px] font-[600] not-italic leading-normal",
  },
  h2: {
    title: "Heading 2",
    description: "14px Medium",
    useCase: "Editor Tabs",
    className: "font-sfProText text-[14px] font-[500] not-italic leading-normal",
  },
  h3: {
    title: "Heading 3",
    description: "13px Heavy",
    useCase: "Title",
    className: "font-sfProText text-[13px] font-[800] not-italic leading-normal",
  },
  h4: {
    title: "Heading 4",
    description: "11px Bold Uppercase",
    useCase: "Sidebar Group, Category, Badge",
    className: "font-sfProText text-[11px] font-[700] uppercase not-italic leading-normal",
  },
  h5: {
    title: "Heading 5",
    description: "11px Medium Uppercase",
    useCase: "Sidebar Title, Panel Tabs",
    className: "font-sfProText text-[11px] font-[500] uppercase not-italic leading-normal",
  },
  h6: {
    title: "Heading 6",
    description: "11px Heavy",
    useCase: "Debugger list item",
    className: "font-sfProText text-[11px] font-[800] not-italic leading-normal",
  },
  "body-1": {
    title: "Body 1",
    description: "13px Medium",
    useCase: "Body, Input, Ext Desc",
    className: "font-sfProText text-[13px] font-[500] not-italic leading-normal",
  },
  "body-2": {
    title: "Body 2",
    description: "12px Medium",
    useCase: "Statusbar, Error validation",
    className: "font-sfProText text-[12px] font-[500] not-italic leading-normal",
  },
  "label-1": {
    title: "Label 1",
    description: "14px Medium",
    useCase: "Ext publisher id",
    className: "font-sfProText text-[14px] font-[500] not-italic leading-[155.137%]",
  },
  "label-2": {
    title: "Label 2",
    description: "12px Bold",
    useCase: "Ext Author",
    className: "font-sfProText text-[12px] font-[700] not-italic leading-[155.137%]",
  },
  "label-3": {
    title: "Label 3",
    description: "11px Medium",
    useCase: "Extension version, meta",
    className: "font-sfProText text-[11px] font-[500] not-italic leading-[100%]",
  },
  "label-4": {
    title: "Label 4",
    description: "9px Bold",
    useCase: "Search badge",
    className: "font-sfProText text-[9px] font-[700] not-italic leading-normal",
  },
  "markdown-h1": {
    title: "Markdown H1",
    description: "26px Normal",
    useCase: "Markdown",
    className: "font-sfProText text-[26px] font-[600] not-italic leading-normal",
  },
  "markdown-h2": {
    title: "Markdown H2",
    description: "20px Normal",
    useCase: "Markdown",
    className: "font-sfProText text-[20px] font-[600] not-italic leading-normal",
  },
  "markdown-h3": {
    title: "Markdown H3",
    description: "15px Normal",
    useCase: "Markdown",
    className: "font-sfProText text-[15px] font-[600] not-italic leading-normal",
  },
  "markdown-h4": {
    title: "Markdown H4",
    description: "13px Bold",
    useCase: "Markdown",
    className: "font-sfProText text-[13px] font-[800] not-italic leading-normal",
  },
  "markdown-h5": {
    title: "Markdown H5",
    description: "11px Bold",
    useCase: "Markdown",
    className: "font-sfProText text-[11px] font-[800] not-italic leading-normal",
  },
  "markdown-h6": {
    title: "Markdown H6",
    description: "9px Bold",
    useCase: "Markdown",
    className: "font-sfProText text-[9px] font-[800] not-italic leading-normal",
  },
  "markdown-paragraph": {
    title: "Markdown Paragraph",
    description: "13px Normal",
    useCase: "Markdown",
    className: "font-sfProText text-[13px] font-[500] not-italic leading-normal",
  },
  "code-1": {
    title: "Code 1",
    description: "12px Regular - Menlo",
    useCase: "Editor",
    className: "font-menlo text-[12px] font-[400] not-italic leading-[150%]",
  },
  "code-2": {
    title: "Code 2",
    description: "12px Bold - Menlo",
    useCase: "Editor bold text",
    className: "font-menlo text-[12px] font-[700] not-italic leading-[151.328%]",
  },
  codicon: {
    title: "",
    description: "16px Codicon",
    useCase: "VS Code Icons",
    className: "text-[16px] font-[400] uppercase not-italic leading-normal",
  },
  seti: {
    title: "",
    description: "20px Seti",
    useCase: "Seti File Icons",
    className: "text-[20px] font-[400] uppercase not-italic leading-normal",
  },
}
