// eslint-disable-next-line import/order
// import { Metadata } from "next"

import { Button } from "@/components/Button/Button"
import { LP_GRID_ITEMS } from "@/lp-items"

// export const metadata: Metadata = {
//   title: "Convey",
//   description: "Generated by create next app",
//   metadataBase: new URL("https://acme.com"),
//   openGraph: {
//     title: "Convey",
//     description: "The React Framework for the Web",
//     url: "https://next-enterprise.vercel.app/",
//     siteName: "Convey",
//     images: [
//       {
//         url: "https://nextjs.org/og.png",
//         width: 800,
//         height: 600,
//         alt: "My custom alt",
//       },
//       {
//         url: "https://nextjs.org/og-alt.png",
//         width: 1800,
//         height: 1600,
//         alt: "My custom alt",
//       },
//     ],
//     locale: "en_US",
//     type: "website",
//   },
//   twitter: {
//     card: "summary_large_image",
//   },
// }

export default function Home() {
  return (
    <>
      <section className="bg-white dark:bg-gray">
        <div className="mx-auto grid max-w-screen-xl px-4 py-8 text-center lg:py-16">
          <div className="mx-auto place-self-center">
            <h1 className="mb-4 max-w-2xl text-4xl font-extrabold leading-none tracking-tight text-base-02 dark:text-base-01 md:text-5xl xl:text-6xl">
              Next.js Enterprise Boilerplate
            </h1>
            <div className="icon">
              <i className="codicon codicon-account"></i> account
            </div>
            <p className="text-gray-500 dark:text-gray-400 mb-6 max-w-2xl font-light md:text-lg lg:mb-8 lg:text-xl">
              Jumpstart your enterprise project with our feature-packed, high-performance Next.js boilerplate!
              Experience rapid UI development, AI-powered code reviews, and an extensive suite of tools for a smooth and
              enjoyable development process.
            </p>
            <Button href="https://github.com/Blazity/next-enterprise" className="mr-3">
              Get started
            </Button>
            <Button
              href="https://vercel.com/new/git/external?repository-url=https://github.com/Blazity/next-enterprise"
              intent="secondary"
            >
              Deploy Now
            </Button>
          </div>
        </div>
      </section>
      <section className="bg-base-01 dark:bg-gray">
        <div className="mx-auto max-w-screen-xl px-4 py-8 sm:py-16 lg:px-6">
          <div className="justify-center space-y-8 md:grid md:grid-cols-2 md:gap-12 md:space-y-0 lg:grid-cols-3">
            {LP_GRID_ITEMS.map((singleItem) => (
              <div key={singleItem.title} className="flex flex-col items-center justify-center text-center">
                <div className="mb-4 flex h-10 w-10 items-center justify-center rounded-full bg-base  p-1.5 text-blue-02 dark:bg-blue lg:h-12 lg:w-12">
                  {singleItem.icon}
                </div>
                <h3 className="dark:text-white mb-2 text-xl font-bold">{singleItem.title}</h3>
                <p className="text-gray-500 dark:text-gray-400">{singleItem.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>
    </>
  )
}
